version: '3.8'

services:
 web:
   build: .
   ports:
     - "7100:7100"
   restart: unless-stopped
   healthcheck:
     test: ["CMD", "curl", "-f", "http://localhost:7100/health"]
     interval: 30s
     timeout: 10s
     retries: 3

 prometheus:
   image: prom/prometheus:latest
   command:
     - '--config.file=/etc/prometheus/prometheus.yml'
     - '--storage.tsdb.path=/prometheus'
     - '--web.console.libraries=/usr/share/prometheus/console_libraries'
     - '--web.console.templates=/usr/share/prometheus/consoles'
   ports:
     - "9090:9090"
   volumes:
     - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
     - ./alerting/rules.yml:/etc/prometheus/rules.yml
     - prometheus_data:/prometheus

 alertmanager:
   image: prom/alertmanager:latest
   ports:
     - "9093:9093"
   volumes:
     - ./alerting/alertmanager.yml:/etc/alertmanager/alertmanager.yml
     - alertmanager_data:/alertmanager

 grafana:
   image: grafana/grafana:latest
   ports:
     - "3000:3000"
   volumes:
     - grafana-storage:/var/lib/grafana
   environment:
     - GF_SECURITY_ADMIN_USER=admin
     - GF_SECURITY_ADMIN_PASSWORD=admin


volumes:
 prometheus_data:
 alertmanager_data:
 grafana-storage:
