global:
  resolve_timeout: 1m

route:
  receiver: 'email'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  group_by: ['alertname']

receivers:
- name: 'email'
  email_configs:
  - to: 'your-email@example.com'
    from: 'alertmanager@example.com'
    smarthost: 'smtp.example.com:587'
    auth_username: 'your-username'
    auth_password: 'your-password'
